### ISSUE TITLE
can't find file 'db'

### ISSUE THREAD

**Issue by timscott** [imdrasil/jennifer.cr#114]
The very first line in `app.cr` is `require "jennifer"` where build fails with the following:

```
> crystal build src/app.cr
Error in src/app.cr:1: while requiring "jennifer"

require "jennifer"
^

in lib/jennifer/src/jennifer.cr:9: while requiring "./jennifer/adapter"

require "./jennifer/adapter"
^

in lib/jennifer/src/jennifer/adapter.cr:1: while requiring "./adapter/base"

require "./adapter/base"
^

in lib/jennifer/src/jennifer/adapter/base.cr:1: while requiring "db": can't find file 'db' relative to '/my/project/dir/lib/jennifer/src/jennifer/adapter'

require "db"
^
```

In shards.yml
```yaml
  jennifer:
    github: imdrasil/jennifer.cr
    version: "~> 0.4.3"
```

I'm new to crystal and to jennifer.cr, so thanks for your patience if I'm missing something obvious.

**Comment by timscott** [comment]
Never mind. I had assumed db driver was built in, and that `require "jennifer/adapter/postgres"` would do the trick. For anyone else getting this error, you need to get the correct db adapter as a shard. In my case:

```yaml
dependencies:
  pg:
    github: will/crystal-pg
```
