### ISSUE TITLE
Task generate:migration was not found

### ISSUE THREAD

**Issue by dcalixto** [imdrasil/jennifer.cr#292]
After setup the shard and tried to create a migration! the logs show this:

```
 sam.cr -- generate:migration CreateUser  ±[●][master]
lib/sam/src/sam.cr:41:5 in 'invoke'
lib/sam/src/sam.cr:77:7 in 'process_tasks'
lib/sam/src/sam.cr:56:7 in 'help'
sam.cr:9:1 in '__crystal_main'
/usr/lib/crystal/crystal/main.cr:97:5 in 'main_user_code'
/usr/lib/crystal/crystal/main.cr:86:7 in 'main'
/usr/lib/crystal/crystal/main.cr:106:3 in 'main'
__libc_start_main
_start
???
Task generate:migration was not found

```
is some config that is missing?

the shard

```
targets:
  simple_api:
    main: src/simple_api.cr

crystal: 0.31.1

license: MIT

dependencies:
  kemal:
    github: kemalcr/kemal
  sam:
    github: imdrasil/sam.cr
    version: 0.3.2
  kemal-auth-token:
    github: akwiatkowski/kemal-auth-token
  jennifer:
    github: imdrasil/jennifer.cr
    version: "~> 0.8.4"
  jennifer_sqlite3_adapter:
    github: imdrasil/jennifer_sqlite3_adapter
```
