### ISSUE TITLE
Unhandled exception: Missing hash key: "" (KeyError)

### ISSUE THREAD

**Issue by lebogan** [imdrasil/jennifer.cr#296]
I am attempting to use this according to the docs:
```
require "jennifer"
require "jennifer/adapter/postgres"
require "../src/models/user.cr"

user = User.create({:name => "Horus", :age => 4000})
puts user.inspect
```

Not sure which hash key is missing. Using Crystal 0.32.1 and Jennifer 0.8.4 with Postgresql.
```
  jennifer:
    github: imdrasil/jennifer.cr
    version: "~> 0.8.4"
  pg:
    github: will/crystal-pg
    version: ~> 0.19.0
  sam:
    github: imdrasil/sam.cr
    version: 0.3.2
```
The error:
```
Unhandled exception: Missing hash key: "" (KeyError)
  from /usr/share/crystal/src/hash.cr:1027:11 in '[]'
  from lib/jennifer/src/jennifer/adapter.cr:72:27 in 'adapter_class'
  from lib/jennifer/src/jennifer/adapter.cr:51:13 in 'adapter'
  from lib/jennifer/src/jennifer/model/resource.cr:165:9 in 'adapter'
  from lib/jennifer/src/jennifer/model/base.cr:385:12 in 'save'
  from lib/jennifer/src/jennifer/model/base.cr:126:9 in 'create'
  from src/mydb.cr:5:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```
The migration portion went well and the table built. Any help here is greatly appreciated.
Thanks.
