### ISSUE TITLE
Error at first usage

### ISSUE THREAD

**Issue by waghanza** [imdrasil/jennifer.cr#300]
Hi @imdrasil,

I have added
```yaml
jennifer:
    github: imdrasil/jennifer.cr
    version: ~> 0.8.4
```
in my list of **dependecies**

When I try to create my first migration (ala _rails_), `crystal lib/jennifer/src/jennifer/sam.cr -- generate:migration Initialization`, I have
```crystal
Showing last frame. Use --error-trace for full trace.

In lib/jennifer/src/jennifer/generators/base.cr:6:36

 6 | getter name : String, args : Sam::Args
                                  ^
Error: undefined constant Sam::Args
```

Regards,
