### ISSUE TITLE
Abstract classes implementation errors

### ISSUE THREAD

**Issue by JakkoJokiranta** [imdrasil/jennifer.cr#362]
Im trying to use version 0.10.0 with crystal 0.36.1
I'm new with crystal, don't know if I'm missing something, or its some kind of merge error

Its giving me some errors when compiling:

```
In lib/jennifer/src/jennifer/relation/base.cr:9:5

 9 | class Base(T, Q) < IRelation
     ^
Error: abstract `def Jennifer::Relation::IRelation#condition_clause(a)` must be implemented by Jennifer::Relation::Base(T, Q)
```

I corrected it locally, but still giving more missing implementations with Jennifer::Migration, and another when class inheritance 
from Jennifer::Model::Base: **def attribute(name, raise_exception),**, which says its not implemented in my final class.

**Comment by imdrasil** [comment]
Jennifer 0.10.0 doesn't support latest (0.36.1) version of crystal. As a temporary workaround you can use `master` branch to resolve this and shortly switch to upcoming `0.11.0` version

**Comment by yunusemredilber** [comment]
I'm getting a similar error:
```
Error: abstract `def Jennifer::Adapter::Base#foreign_key_exists?(from_table, to_table = nil, column = nil, name : String | ::Nil = nil)` must be implemented by Jennifer::SQLite3::Adapter
```

Here is my current lib versions:
```yml
jennifer:
  github: imdrasil/jennifer.cr
  branch: master
jennifer_sqlite3_adapter:
  github: imdrasil/jennifer_sqlite3_adapter
  branch: master
```

Do you have any idea?
